### ISSUE TITLE
End-to-End Training

### ISSUE THREAD

**Issue by Data-Designer** [SSRSGJYD/Feature-Space-Augmentation-for-Long-Tailed-Data#8]
Hi, the author note that his paper is in an end-to-end approach, but your code seems to be in a tripe stage.  I'm confused and wondering how it works in the original paper? Looking forward to your reply.

**Comment by SSRSGJYD** [comment]
According to the paper, there is two phases in the algorithm. For efficiency issues, we implement feature map calculation as a single phase.

**Comment by Data-Designer** [comment]
Many thanks. I re-read the paper and found that the author's description in the Introduction section misunderstood me. Thanks for your reply.
